{
  "appname": {
    "message": "Chrome 接続診断",
    "description": "[CHAR LIMIT=44] String CANNOT be longer than 44 chars under any circumstances or we cannot use the entire translation file. Title of the Chrome App name. [CHAR LIMIT=44]"
  },
  "appname_beta": {
    "message": "Chrome 接続診断（ベータ版）",
    "description": "[CHAR LIMIT=44] String CANNOT be longer than 44 chars under any circumstances or we cannot use the entire translation file. Title of the Chrome App name (Beta). [CHAR LIMIT=44]"
  },
  "appname_dev": {
    "message": "Chrome 接続診断（開発版）",
    "description": "[CHAR LIMIT=44] String CANNOT be longer than 44 chars under any circumstances or we cannot use the entire translation file. Title of the Chrome App name (Dev). [CHAR LIMIT=44]"
  },
  "apptitle": {
    "message": "接続診断",
    "description": "HTML and header page title. [CHAR LIMIT=44]"
  },
  "apptitle_ucase": {
    "message": "接続診断",
    "description": "HTML and header page title."
  },
  "aria_label_settings": {
    "message": "設定",
    "description": "ARIA label for the settings button."
  },
  "aria_label_maximize": {
    "message": "最大化",
    "description": "ARIA label for the maximize button."
  },
  "aria_label_restore": {
    "message": "復元",
    "description": "ARIA label for the restore button."
  },
  "aria_label_close": {
    "message": "閉じる",
    "description": "ARIA label for the close button."
  },
  "aria_label_scroll_up": {
    "message": "上にスクロール",
    "description": "ARIA label for the scroll up button."
  },
  "aria_label_scroll_down": {
    "message": "下にスクロール",
    "description": "ARIA label for the scroll down button."
  },
  "network_settings_wireless_connection": {
    "message": "Wi-Fi",
    "description": "Description of a wireless connection"
  },
  "network_settings_ethernet_connection": {
    "message": "イーサネット",
    "description": "Description of a wired network connection"
  },
  "network_settings_ssid": {
    "message": "SSID",
    "description": "Attribute label for network ssid"
  },
  "network_settings_signal_strength": {
    "message": "信号強度",
    "description": "Attribute label for network signal strength"
  },
  "network_settings_mac_address": {
    "message": "MAC アドレス",
    "description": "Attribute label for mac address"
  },
  "network_settings_ip_address": {
    "message": "IP アドレス",
    "description": "Attribute label for ip address of the machine"
  },
  "network_settings_subnet_mask": {
    "message": "サブネット マスク",
    "description": "Attribute label for subnet mask"
  },
  "network_settings_gateway": {
    "message": "ゲートウェイ",
    "description": "Attribute label for the network gateway"
  },
  "network_settings_dns": {
    "message": "DNS",
    "description": "Attribute label for the dns servers"
  },
  "network_settings_dns_not_detected": {
    "message": "DNS を検出できません",
    "description": "Message when the DNS nameservers cannot be detected"
  },
  "network_settings_connection_title": {
    "message": "接続",
    "description": "Attribute label for the Connection."
  },
  "network_settings_connection": {
    "message": "接続",
    "description": "Used to describe a network connection. Example use: Wi-Fi connection secure."
  },
  "network_settings_network_secure": {
    "message": "（安全度: 高）",
    "description": "Used to describe a network connection. Example use: Wi-Fi connection secure."
  },
  "network_settings_network_insecure": {
    "message": "（安全度: 低）",
    "description": "Used to describe a network connection. Example use: Wi-Fi connection secure."
  },
  "all_test_groups_summary_title": {
    "message": "ネットワーク接続テスト",
    "description": "Title for the all test group page."
  },
  "captive_portal_test_group_summary_title": {
    "message": "キャプティブ ポータル",
    "description": "Title for the connectivity test group that is captive portal"
  },
  "local_network_test_group_summary_title": {
    "message": "ローカル ネットワーク",
    "description": "Title for the connectivity test group that is local network"
  },
  "dns_test_group_summary_title": {
    "message": "DNS",
    "description": "Title for the connectivity test group that is DNS"
  },
  "firewall_test_group_summary_title": {
    "message": "ファイアウォール",
    "description": "Title for the connectivity test group that is firewall"
  },
  "google_services_test_group_summary_title": {
    "message": "Google のサービス",
    "description": "Title for the connectivity test group that is Google services"
  },
  "tests_running_message": {
    "message": "テストを実行しています。これには数分かかることがあります...",
    "description": "Text to inform the user the tests are running."
  },
  "tests_failed_message": {
    "message": "接続診断テストの実行中にエラーが発生しました。歯車アイコンをクリックし、[テストを再実行] を選択してください。エラーが解消しない場合は、[フィードバックを送信] をクリックして状況をお知らせください。",
    "description": "Test to display to inform the user that the tests failed"
  },
  "footer_send_feedback": {
    "message": "フィードバックを送信",
    "description": "Text in the bottom footer bar to send feedback"
  },
  "footer_network_settings": {
    "message": "ネットワーク設定",
    "description": "Text in the bottom footer bar to view network settings"
  },
  "footer_run_diagnostics": {
    "message": "診断を実行",
    "description": "Text in the bottom footer bar to run CCD diagnostics"
  },
  "footer_rerun_diagnostics": {
    "message": "診断を再実行",
    "description": "Text in the bottom footer bar to rerun CCD diagnostics"
  },
  "footer_go_back": {
    "message": "戻る",
    "description": "Text in the bottom footer bar to go back [CHAR LIMIT=20]"
  },
  "result_no_connectivity_problems": {
    "message": "ネットワーク接続は正常に動作しているようです。",
    "description": "Tests did not find a problem"
  },
  "setting_show_passing_test": {
    "message": "合格したテストを表示",
    "description": "The setting that toggles whether to show passing tests [CHAR LIMIT=25]"
  },
  "setting_hide_passing_test": {
    "message": "合格したテストを非表示",
    "description": "The setting that toggles whether to show passing tests [CHAR LIMIT=25]"
  },
  "setting_rerun_tests": {
    "message": "診断を再実行",
    "description": "The setting that allows a user to re-runs diagnostic tests [CHAR LIMIT=25]"
  },
  "setting_send_feedback": {
    "message": "フィードバックを送信...",
    "description": "The setting that prompts the user to send feedback [CHAR LIMIT=25]"
  },
  "setting_about": {
    "message": "情報",
    "description": "The setting that lets the user learn about the app [CHAR LIMIT=25]"
  },
  "about_app": {
    "message": "アプリについて",
    "description": "The title for the About App feature"
  },
  "about_version_num": {
    "message": "バージョン: ",
    "description": "The version number of the application"
  },
  "passing_tests_title": {
    "message": "合格したテスト",
    "description": "Page section title for tests that passed"
  },
  "passing_test_title": {
    "message": "合格したテスト",
    "description": "Page section title for test that passed"
  },
  "warning_tests_title": {
    "message": "警告",
    "description": "Page section title for tests that gave warnings"
  },
  "warning_test_title": {
    "message": "警告",
    "description": "Page section title for test that gave warning"
  },
  "test_result_log_test_name": {
    "message": "テスト名: ",
    "description": "In the logs for a test, print out the test name"
  },
  "test_result_log_test_id": {
    "message": "テスト ID: ",
    "description": "In the logs for a test, print out the test ID"
  },
  "test_result_log_test_verdict": {
    "message": "テスト結果: ",
    "description": "In the logs for a test, print out the test verdict"
  },
  "test_result_log_verdict_no_problem": {
    "message": "問題は検出されませんでした",
    "description": "In the logs for a test, print out the test verdict"
  },
  "test_result_log_verdict_problem": {
    "message": "問題が検出されました",
    "description": "In the logs for a test, print out the test verdict"
  },
  "test_result_log_verdict_potential_problem": {
    "message": "潜在的な問題が検出されました",
    "description": "In the logs for a test, print out the test verdict"
  },
  "test_result_log_verdict_failure_occurred": {
    "message": "テストを実行できません",
    "description": "In the logs for a test, print out the test verdict"
  },
  "test_result_show_logs": {
    "message": "ログを表示...",
    "description": "Link to show logs"
  },
  "test_result_hide_logs": {
    "message": "ログを非表示...",
    "description": "Link to hide logs"
  },
  "test_result_copy_logs": {
    "message": "結果のログをコピー",
    "description": "Link to copy result logs"
  },
  "test_result_log_summary": {
    "message": "概要",
    "description": "Show header in the logs for the summary section"
  },
  "test_result_log_criteria": {
    "message": "条件",
    "description": "Show a header in the logs for the criteria section"
  },
  "test_result_log_details": {
    "message": "詳細",
    "description": "Show a header in the logs for the details section"
  },
  "test_result_log_support_details": {
    "message": "サポートの詳細",
    "description": "Show a header in the logs for the support details section"
  },
  "tests_summary_group_status_passed": {
    "message": "合格",
    "description": "Current status of the group of tests if the group of tests passed [CHAR LIMIT=12]"
  },
  "tests_summary_group_status_failed": {
    "message": "不合格",
    "description": "Current status of the group of tests if the group of tests failed [CHAR LIMIT=12]"
  },
  "tests_summary_group_status_queued": {
    "message": "待機",
    "description": "Current status of the group of tests if the group of tests are queued [CHAR LIMIT=12]"
  },
  "tests_summary_group_status_warning": {
    "message": "警告",
    "description": "Current status of the group of tests if the group of tests resulted in a warning [CHAR LIMIT=12]"
  },
  "tests_summary_group_status_running": {
    "message": "実行中",
    "description": "Current status of the group of tests if the group of tests is running [CHAR LIMIT=12]"
  },
  "tests_summary_group_status_canceled": {
    "message": "キャンセル",
    "description": "Current status of the group of tests if the group of tests is canceled [CHAR LIMIT=12]"
  },
  "tests_summary_sub_group_no_results": {
    "message": "現時点でテスト結果はありません。",
    "description": "Indicate that there are no test results available for a specific group of connectivity tests."
  },
  "tests_summary_sub_group_tests_still_running": {
    "message": "追加テストが完了していません。完了時に結果が表示されます。",
    "description": "Indicate that connectivity tests for a specific group are still running"
  },
  "tests_summary_sub_group_tests_title": {
    "message": "テスト",
    "description": "Suffix for a test group name (e.g., 'Network tests', 'Google service tests', 'Firewall tests', 'Captive portal tests')"
  },
  "udpsocket_log_parsed_udp_response": {
    "message": "UDP ソケットから未処理のデータを受信しました: ",
    "description": "Log data from UDP socket"
  },
  "udpsocket_log_parsed_response_size": {
    "message": "UDP ソケットからデータを正常に読み取りました。サイズ（バイト）: ",
    "description": "Log received UDP packet size"
  },
  "udpsocket_log_error_reading_udp_data": {
    "message": "UDP データの読み取り中にエラーが発生しました。エラーコード: ",
    "description": "Log error reading UDP data"
  },
  "udpsocket_log_successfully_sent_data": {
    "message": "データを正常に送信しました。サイズ（バイト）: ",
    "description": "Log successfully sent UDP data"
  },
  "udpsocket_log_preparing_to_send_data": {
    "message": "UDP ソケットデータの送信を準備しています。サイズ（バイト）: ",
    "description": "Log preparing to send UDP data"
  },
  "udpsocket_log_socket_created": {
    "message": "UDP ソケットを作成しています。番号 / ホスト / ポート: ",
    "description": "Log UDP socket created"
  },
  "udpsocket_log_udp_timeout_setting": {
    "message": "UDP のタイムアウトを設定しています。長さ（ミリ秒）: ",
    "description": "Log UDP timeout setting"
  },
  "telnet_log_parsed_tcp_response": {
    "message": "TCP ソケットから未処理のデータを受信しました: ",
    "description": "Log data from TCP socket"
  },
  "telnet_log_parsed_response_size": {
    "message": "TCP ソケットからデータを正常に読み取りました。サイズ（バイト）: ",
    "description": "Log received TCP size"
  },
  "telnet_log_error_reading_tcp_data": {
    "message": "TCP データの読み取り中にエラーが発生しました。エラーコード: ",
    "description": "Log error reading TCP data"
  },
  "telnet_log_successfully_sent_data": {
    "message": "データを正常に送信しました。サイズ（バイト）: ",
    "description": "Log successfully sent TCP data"
  },
  "telnet_log_preparing_to_send_data": {
    "message": "データの送信を準備しています。サイズ（バイト）: ",
    "description": "Log preparing to send TCP data"
  },
  "telnet_log_connection_established": {
    "message": "TCP 接続を確立しました。ホスト / ポート / ステータス コード: ",
    "description": "Log connection established"
  },
  "telnet_log_connection_failure": {
    "message": "TCP 接続に失敗しました。ホスト / ポート / ステータス コード: ",
    "description": "Log TCP connection failure"
  },
  "telnet_log_connection_failure_unknown": {
    "message": "接続エラー。理由: 不明",
    "description": "Log TCP connection failure reason unknown"
  },
  "telnet_log_connection_established_successfully": {
    "message": "TCP 接続を正常に確立しました。ホスト / ポート: ",
    "description": "Log TCP connection established successfully"
  },
  "telnet_log_connection_failure_timeout": {
    "message": "接続エラー。理由: タイムアウト",
    "description": "Log TCP connection failure due to timeout"
  },
  "telnet_log_connection_failure_refused": {
    "message": "接続エラー。理由: 接続拒否",
    "description": "Log TCP connection failure due to refusal"
  },
  "telnet_log_socket_created": {
    "message": "TCP ソケットを作成しています。番号 / ホスト / ポート: ",
    "description": "Log TCP socket created"
  },
  "telnet_log_tcp_timeout_setting": {
    "message": "TCP のタイムアウトを設定しています。長さ（ミリ秒）: ",
    "description": "Log TCP timeout setting"
  },
  "chromeinternetdisconnectedtest_name": {
    "message": "Chrome インターネット接続テスト",
    "description": "Name for the Chrome Internet Disconnected test"
  },
  "chromeinternetdisconnectedtest_problem_title": {
    "message": "ネットワークに接続していません",
    "description": "Title for when a problem is found with the Chrome internet connection."
  },
  "chromeinternetdisconnectedtest_noproblem_title": {
    "message": "インターネット接続を使用できます",
    "description": "Title for when no problem is found with the Chrome internet connection."
  },
  "chromeinternetdisconnectedtest_problem_subtitle": {
    "message": "Chrome はネットワークに接続していません。オペレーティング システムのネットワーク設定をご確認ください。",
    "description": "Subtitle for when a problem is found with the Chrome internet connection."
  },
  "chromeinternetdisconnectedtest_noproblem_subtitle": {
    "message": "Chrome ブラウザでインターネット接続を使用できます。",
    "description": "Subtitle for when no problem is found with the Chrome internet connection."
  },
  "chromeinternetdisconnectedtest_no_problem_threshold": {
    "message": "インターネット非接続ステータス コードを返す TCP ソケットの割合（下回ったとき、問題なしという結果を表示）: ",
    "description": "Logger record for percent of TCP sockets that return internet disconnected in order for test to fail"
  },
  "chromeinternetdisconnectedtest_problem_threshold": {
    "message": "インターネット非接続ステータス コードを返す TCP ソケットの割合（等しいか上回ったとき、問題ありという結果を表示）: ",
    "description": "Logger record for percent of TCP sockets that return internet disconnected in order for test to fail"
  },
  "chromeinternetdisconnectedtest_log_connection_status_known": {
    "message": "Chrome のインターネット接続テストで次の TCP ステータス コードが返されました: ",
    "description": "Logger record for when a TCP connection status code is known in the Chrome internet connection test."
  },
  "chromeinternetdisconnectedtest_log_connection_beginning": {
    "message": "TCP 接続を試行します。# / ホスト名 / ポート: ",
    "description": "Logger record for when a TCP connection to a specific host and port is about to begin"
  },
  "chromeosinternetdisconnectedtest_name": {
    "message": "Chrome OS インターネット接続テスト",
    "description": "Name for the ChromeOS Internet Disconnected test"
  },
  "chromeosinternetdisconnectedtest_problem_title": {
    "message": "ネットワークに接続していません",
    "description": "Title for when a problem is found with the ChromeOS internet connection."
  },
  "chromeosinternetdisconnectedtest_noproblem_title": {
    "message": "インターネット接続を使用できます",
    "description": "Title for when no problem is found with the ChromeOS internet connection."
  },
  "chromeosinternetdisconnectedtest_problem_subtitle": {
    "message": "この Chromebook はネットワークに接続していません。ステータス トレイから使用可能なネットワークに接続してください。",
    "description": "Subtitle for when a problem is found with the ChromeOS internet connection."
  },
  "chromeosinternetdisconnectedtest_noproblem_subtitle": {
    "message": "インターネット接続を使用できます。",
    "description": "Subtitle for when no problem is found with the ChromeOS internet connection."
  },
  "chromeosinternetdisconnectedtest_no_problem_threshold": {
    "message": "接続しているネットワーク インターフェースが接続ステータス コードを返した場合は、問題なしという結果が表示されます",
    "description": "Condition under which the ChromeOS internet disconnected test returns a no problem result"
  },
  "chromeosinternetdisconnectedtest_problem_threshold": {
    "message": "接続しているネットワーク インターフェースが次の非接続ステータス コードを返した場合は、問題ありという結果が表示されます: ",
    "description": "Condition under which the ChromeOS internet disconnected test returns a problem result"
  },
  "chromeosinternetdisconnectedtest_log_available_networks": {
    "message": "検出された使用可能なネットワークの数: ",
    "description": "Logger record for how many networks chrome.networkingPrivate found."
  },
  "chromeversiontest_name": {
    "message": "Chrome のバージョン テスト",
    "description": "Name for the Chrome Version test"
  },
  "chromeversiontest_problem_title": {
    "message": "Google Chrome は最新バージョンではありません",
    "description": "Title for when a problem is found with the Chrome version."
  },
  "chromeversiontest_noproblem_title": {
    "message": "Google Chrome は最新バージョンです",
    "description": "Title for when no problem is found with the Chrome version."
  },
  "chromeversiontest_problem_subtitle": {
    "message": "ご使用の Google Chrome は最新バージョンではありません。このため、既知のバグの修正が一部未適用となっており、接続の問題が発生する可能性があります。ブラウザ ツールバーの Chrome メニューから [Google Chrome について] を選択して Chrome を更新してください。",
    "description": "Subtitle for when a problem is found with the Chrome version."
  },
  "chromeversiontest_noproblem_subtitle": {
    "message": "ご使用の Google Chrome は最新バージョンです。接続に関する既知のバグはすべて修正されています。",
    "description": "Subtitle for when no problem is found with the Chrome version."
  },
  "chromeversiontest_raw_useragent": {
    "message": "未処理のブラウザ ユーザー エージェント: ",
    "description": "Raw browser user-agent"
  },
  "chromeversiontest_short_browser": {
    "message": "ブラウザのバージョン番号（短縮）: ",
    "description": "Short browser version number"
  },
  "chromeversiontest_full_browser": {
    "message": "ブラウザのバージョン番号（完全）: ",
    "description": "Short browser version number"
  },
  "chromeversiontest_no_problem_version": {
    "message": "Chrome のバージョン番号のしきい値（等しいか上回ったとき、問題なしという結果を表示）: ",
    "description": "Logger record for Chrome version test for which we render a no problem verdict."
  },
  "chromeversiontest_problem_version": {
    "message": "Chrome のバージョン番号のしきい値（下回ったとき、問題ありという結果を表示）: ",
    "description": "Logger record for Chrome version test for which we render a problem verdict."
  },
  "chromeosversiontest_name": {
    "message": "Chrome OS のバージョン名",
    "description": "Name for the ChromeOS Version test"
  },
  "chromeosversiontest_problem_title": {
    "message": "Chrome OS は最新ではありません",
    "description": "Title for when a problem is found with the ChromeOS version."
  },
  "chromeosversiontest_noproblem_title": {
    "message": "Chrome OS は最新です",
    "description": "Title for when no problem is found with the ChromeOS version."
  },
  "chromeosversiontest_problem_subtitle": {
    "message": "ご使用の Chrome OS は最新バージョンではありません。このため、既知のバグの修正が一部未適用となっており、接続の問題が発生する可能性があります。",
    "description": "Subtitle for when a problem is found with the ChromeOS version."
  },
  "chromeosversiontest_noproblem_subtitle": {
    "message": "ご使用の Chrome OS は最新バージョンです。接続に関する既知のバグはすべて修正されています。",
    "description": "Subtitle for when no problem is found with the ChromeOS version."
  },
  "chromeosversiontest_problem_record_log": {
    "message": "Chrome OS のバージョン テストで問題が検出されました。Chrome OS のバージョンが最新ではありません。現在の最小バージョン: ",
    "description": "Log record for recording that a problem existed with the ChromeOS version."
  },
  "chromeosversiontest_noproblem_record_log": {
    "message": "Chrome OS のバージョン テストで問題は検出されませんでした。Chrome OS のバージョンは最新です。現在の最小バージョン: ",
    "description": "Log record for recording that no problem existed with the ChromeOS version."
  },
  "chromeosversiontest_raw_useragent": {
    "message": "未処理のブラウザ ユーザー エージェント: ",
    "description": "Raw browser user-agent"
  },
  "chromeosversiontest_short_platform": {
    "message": "Chrome OS のプラットフォーム番号（短縮）: ",
    "description": "Short ChromeOS platform number parsed from the HTTP user-agent string"
  },
  "chromeosversiontest_full_platform": {
    "message": "Chrome OS のプラットフォーム番号（完全）: ",
    "description": "Full ChromeOS platform number parsed from the HTTP user-agent string"
  },
  "chromeosversiontest_no_problem_version": {
    "message": "Chrome OS のプラットフォーム番号のしきい値（等しいか上回ったとき、問題なしという結果を表示）: ",
    "description": "Logger record for ChromeOS platform number for which we render a no problem verdict."
  },
  "chromeosversiontest_problem_version": {
    "message": "Chrome OS のプラットフォーム番号のしきい値（下回ったとき、問題ありという結果を表示）:",
    "description": "Logger record for ChromeOS platform number for which we render a problem verdict."
  },
  "resolverpresenttest_name": {
    "message": "リゾルバ応答テスト",
    "description": "Name for the Resolver Present test"
  },
  "resolverpresenttest_problem_title": {
    "message": "使用できる（機能する）DNS サーバーがありません",
    "description": "Title for when a problem is found with the DNS Resolver Present test."
  },
  "resolverpresenttest_noproblem_title": {
    "message": "DNS サーバーを使用できます",
    "description": "Title for when no problem is found with the DNS Resolver Present test."
  },
  "resolverpresenttest_problem_subtitle": {
    "message": "DNS サーバーはホスト名（例: www.google.com）を IP アドレスに変換します。ブラウザでウェブサイトを読み込むには、接続先の IP アドレスが必要です。DNS サーバーが動作していないため、アクセスしようとしているウェブサイトの IP アドレスを Chrome で特定できません。ISP またはネットワーク管理者までお問い合わせください。",
    "description": "Subtitle for when a problem is found with the DNS Resolver Present test."
  },
  "resolverpresenttest_noproblem_subtitle": {
    "message": "ホスト名（例: www.google.com）を IP アドレスに正常に変換した DNS サーバーが Chrome で検出されました。",
    "description": "Subtitle for when no problem is found with the DNS Resolver Present test."
  },
  "resolverpresenttest_gettinghostname": {
    "message": "ホスト名の解決を試行します: ",
    "description": "Logger record denoting that the resolverpresenttest is about to resolve a hostname"
  },
  "resolverpresenttest_testcompleted": {
    "message": "DNS サーバーから DNS クエリの結果が返されました。",
    "description": "Logger record denoting that the resolverpresenttest is complete"
  },
  "resolverpresenttest_testfailed": {
    "message": "DNS サーバーから結果が返されませんでした。",
    "description": "Logger record denoting that the resolverpresenttest failed as the resolver did not return any result (even an error)"
  },
  "resolverpresenttest_hostnameresult": {
    "message": "ホスト名が次の IP アドレスに変換されました: ",
    "description": "Logger record denoting the IP result that the DNS resolved the hostname to"
  },
  "resolverpresenttest_criteria_success": {
    "message": "DNS リゾルバテストは、単独の DNS クエリを実行し、有効なレスポンスが返された場合は合格という結果を返します。",
    "description": "Logger record denoting the successful DNS query status code result"
  },
  "resolverpresenttest_criteria_failure": {
    "message": "DNS リゾルバテストは、単独の DNS クエリを実行し、有効なレスポンスが返されなかった場合は失敗という結果を返します。",
    "description": "Logger record denoting the failed DNS query status code result"
  },
  "resolverpresenttest_log_statuscodesuccess": {
    "message": "DNS サーバーから成功のステータス コードが返されました: ",
    "description": "Logger record denoting the successful DNS query status code result"
  },
  "resolverpresenttest_log_statuscodefailure": {
    "message": "DNS サーバーから問題を示すステータス コードが返されました: ",
    "description": "Logger record denoting the failed DNS query status code result"
  },
  "resolverlatencytest_name": {
    "message": "リゾルバ待ち時間テスト",
    "description": "Name for the Resolver Latency test"
  },
  "resolverlatencytest_problem_title": {
    "message": "DNS 解決に時間がかかりすぎました",
    "description": "Title for when a problem is found with the DNS Latency test."
  },
  "resolverlatencytest_potentialproblem_title": {
    "message": "DNS 解決に平均以上の時間がかかりました",
    "description": "Title for when a potential problem is found with the DNS Latency test."
  },
  "resolverlatencytest_noproblem_title": {
    "message": "迅速な DNS レスポンスを受信しました",
    "description": "Title for when no problem is found with the DNS Latency test."
  },
  "resolverlatencytest_problem_subtitle": {
    "message": "DNS サーバーは迅速に応答しませんでした。DNS サーバーはホスト名（例: www.google.com）を IP アドレスに変換する役割を果たします。ブラウザでウェブサイトを読み込むには、接続先の IP アドレスが必要です...",
    "description": "Subtitle for when a problem is found with the DNS Latency test."
  },
  "resolverlatencytest_potential_problem_subtitle": {
    "message": "DNS サーバーは十分な速さでは応答しませんでした。DNS サーバーはホスト名（例: www.google.com）を IP アドレスに変換する役割を果たします。ブラウザでウェブサイトを読み込むには、接続先の IP アドレスが必要です。",
    "description": "Subtitle for when a potential problem is found with the DNS Latency test."
  },
  "resolverlatencytest_noproblem_subtitle": {
    "message": "DNS サーバーはリクエストに対して迅速に応答しました。DNS サーバーはホスト名（例: www.google.com）を IP アドレスに変換する役割を果たします。ブラウザでウェブサイトを読み込むには、接続先の IP アドレスが必要です。",
    "description": "Subtitle for when no problem is found with the DNS Latency test."
  },
  "resolverlatencytest_beginning_resolution": {
    "message": "ホスト名の解決を試行します。#: ",
    "description": "Logger record for noting that DNS resolution is beginning."
  },
  "resolverlatencytest_queryresult_received": {
    "message": "DNS 解決の結果を受信しました。テスト番号 / 現在の時刻 / 所要時間（ミリ秒） / 開始時刻（ミリ秒）: ",
    "description": "Logger record for noting that DNS resolution is beginning."
  },
  "resolverlatencytest_total_resolution_time": {
    "message": "すべてのテストで DNS 解決にかかった合計時間（ミリ秒）: ",
    "description": "Logger record for noting the total DNS resolution time."
  },
  "resolverlatencytest_total_hosts_resolved": {
    "message": "解決された DNS ホストの合計数: ",
    "description": "Logger record for noting the total hosts resolved."
  },
  "resolverlatencytest_average_resolution_time": {
    "message": "DNS 解決にかかった平均時間（ミリ秒）: ",
    "description": "Logger record for noting the average DNS resolution time."
  },
  "resolverlatencytest_no_problem_time": {
    "message": "DNS 解決にかかった平均時間（ミリ秒）のベンチマーク（下回ったとき、問題なしという結果を表示）: ",
    "description": "Logger record for dns resolution time for which we render a no problem verdict."
  },
  "resolverlatencytest_potential_problem_time": {
    "message": "DNS 解決にかかった平均時間（ミリ秒）のベンチマーク（範囲内のとき、問題の可能性ありという結果を表示）: ",
    "description": "Logger record for dns resolution time for which we render a potential problem verdict."
  },
  "resolverlatencytest_problem_time": {
    "message": "DNS 解決にかかった平均時間（ミリ秒）のベンチマーク（上回ったとき、問題ありという結果を表示）: ",
    "description": "Logger record for dns resolution time for which we render a problem verdict."
  },
  "dnspoisoningtest_name": {
    "message": "DNS 汚染テスト",
    "description": "Name for DNS poisoning test."
  },
  "dnspoisoningtest_noproblem_title": {
    "message": "DNS サーバーから想定どおりの結果が返されました",
    "description": "Title for when no problem is found with the DNS poisoning test."
  },
  "dnspoisoningtest_noproblem_subtitle": {
    "message": "DNS の結果は想定どおりです。正確であると考えられます",
    "description": "Subtitle for when no problem is found with the DNS poisoning test."
  },
  "dnspoisoningtest_problem_title": {
    "message": "DNS の結果は想定外です。汚染されている可能性があります",
    "description": "Title for when a problem is found with the DNS poisoning test."
  },
  "dnspoisoningtest_problem_subtitle": {
    "message": "汚染された DNS レスポンスが返されました。汚染された DNS サーバーが、不正な IP アドレスを返すことにより、意図しないホストにトラフィックを誘導している可能性があります。",
    "description": "Subtitle for when a problem is found with the DNS poisoning test."
  },
  "dnspoisoningtest_problem_threshold": {
    "message": "想定した IP アドレスがリゾルバから返されなかった場合、DNS の結果は汚染されていると考えられます。",
    "description": "Log record for the threshold of a problem"
  },
  "dnspoisoningtest_no_problem_threshold": {
    "message": "想定どおりの IP アドレスがリゾルバから返された場合、DNS の結果は汚染されていないと考えられます。",
    "description": "Log record for the threshold of no problem"
  },
  "dnspoisoningtest_beginning_resolution": {
    "message": "テスト # / テストホスト名: ",
    "description": "Logger record for noting a new DNS resolution attempt."
  },
  "dnspoisoningtest_no_addr_returned": {
    "message": "テストで DNS アドレスのフィールドが返されませんでした（null に設定されています）",
    "description": "Logger record for when DNS resolution returns no address field."
  },
  "dnspoisoningtest_noresult_code_returned": {
    "message": "テスト。結果のステータス コードがありません。テストに失敗したためテストを中止します。",
    "description": "Logger record for when DNS resolution returns no result status code field."
  },
  "dnspoisoningtest_log_statuscode_returned": {
    "message": "テストで次のステータス コードが返されました: ",
    "description": "Logger record for DNS response status code."
  },
  "dnspoisoningtest_log_address_returned": {
    "message": "解決済み DNS アドレスが返されました: ",
    "description": "Logger record for DNS response address."
  },
  "tcpfirewalltest_name": {
    "message": "TCP ファイアウォール テスト",
    "description": "Name for TCP Firewall test"
  },
  "tcpfirewalltest_problem_title": {
    "message": "インターネット トラフィックは次のポートでブロックされています: ",
    "description": "Title for when a problem is found with the TCP Firewall test."
  },
  "tcpfirewalltest_potentialproblem_title": {
    "message": "インターネット トラフィックは次のポートでブロックされているようです: ",
    "description": "Title for when a potential problem is found with the TCP Firewall test."
  },
  "tcpfirewalltest_noproblem_title": {
    "message": "インターネット トラフィックは次のポートで許可されています: ",
    "description": "Title for when no problem is found with the TCP Firewall test."
  },
  "tcpfirewalltest_problem_subtitle": {
    "message": "ネットワークで、よく使用されるインターネット接続に対し制限がかけられています。",
    "description": "Subtitle for when a problem is found with the TCP Firewall test."
  },
  "tcpfirewalltest_potentialproblem_subtitle": {
    "message": "ネットワークで、よく使用されるインターネット接続に対し制限がかけられているようです。",
    "description": "Subtitle for when a potential problem is found with the TCP Firewall test."
  },
  "tcpfirewalltest_noproblem_subtitle": {
    "message": "次のポートで接続に成功しました: ",
    "description": "Subtitle for when no problem is found with the TCP Firewall test."
  },
  "tcpfirewalltest_log_connection_about_begun": {
    "message": "TCP 接続を試行します。# / ホスト名 / ポート: ",
    "description": "Logger record for when a TCP connection to a specific host and port is about to begin"
  },
  "tcpfirewalltest_log_connection_status_known": {
    "message": "TCP ファイアウォールのテストで次の TCP のステータス コードが返されました: ",
    "description": "Logger record for when a TCP connection status code is known"
  },
  "tcpfirewalltest_log_analysis_summary": {
    "message": "ファイアウォール テストの結果: 実行されたテスト / 確認されたポート / 接続に失敗した数: ",
    "description": "Logger record for summarizing the analysis of the various TCP connections made in a test"
  },
  "tcpfirewalltest_log_count_failed_attempt": {
    "message": "接続テスト試行に失敗しました。Chrome ネットワーク スタックから TCP の成功のステータス コードは返されませんでした。代わりに次のステータス コードが返されました: ",
    "description": "Logger record for denoting failure of a TCP connection"
  },
  "tcpfirewalltest_log_dns_broken": {
    "message": "検出された DNS リゾルバは使用できません。このため、ファイアウォールが存在するかどうかを判定できません",
    "description": "Logger record for when TCP connections seem to fail due to DNS resolver not working"
  },
  "tcpfirewalltest_log_network_disconnected": {
    "message": "検出されたネットワークは使用できません。このため、ファイアウォールが存在するかどうかを判定できません",
    "description": "Logger record for when TCP connections seem to reveal that the network is unavailable"
  },
  "tcpfirewalltest_no_problem_threshold": {
    "message": "TCP 接続テストの結果で失敗の割合が次と同じか下回ったとき、問題なしと表示されます: ",
    "description": "Logger record for TCP firewall test for which we render a no problem verdict."
  },
  "tcpfirewalltest_problem_threshold": {
    "message": "TCP 接続テストの結果で失敗の割合が次と同じとき、問題ありと表示されます: ",
    "description": "Logger record for TCP firewall test for which we render a problem verdict."
  },
  "tcpfirewalltest_potential_problem_threshold": {
    "message": "TCP 接続テストの結果で失敗の割合が次の範囲内にあるとき、問題の可能性ありと表示されます: ",
    "description": "Logger record for TCP firewall test for which we render a potential problem verdict."
  },
  "captiveportalhttptest_name": {
    "message": "HTTP キャプティブ ポータル テスト",
    "description": "Name for the Captive Portal HTTP test"
  },
  "captiveportalhttptest_problem_title": {
    "message": "インターネット トラフィックはキャプティブ ポータルによってブロックされています",
    "description": "Title for when a problem is found with the HTTP captive portal test."
  },
  "captiveportalhttptest_potentialproblem_title": {
    "message": "HTTP キャプティブ ポータルを適切にテストできません",
    "description": "Title for when potential problem is found with the HTTP captive portal test."
  },
  "captiveportalhttptest_noproblem_title": {
    "message": "オープン インターネット アクセスが検出されました",
    "description": "Title for when no problem is found with the HTTP captive portal test."
  },
  "captiveportalhttptest_problem_subtitle": {
    "message": "キャプティブ ポータルとは、インターネットを自由に閲覧するアクセス権を得る前に、ネットワークのユーザーによる表示と操作が必要なウェブサイトのことです。ご利用のネットワークでキャプティブ ポータルが見つかりました。インターネットへの無制限のアクセスはブロックされています。",
    "description": "Subtitle for when a problem is found with the HTTP captive portal test."
  },
  "captiveportalhttptest_potentialproblem_subtitle": {
    "message": "HTTP キャプティブ ポータルのテストを妨げる問題があります。この問題は一般に、すべてのネットワーク トラフィックが拒否またはブロックされている場合に発生します。",
    "description": "Subtitle for when potential problem is found with the HTTP captive portal test."
  },
  "captiveportalhttptest_noproblem_subtitle": {
    "message": "オープン インターネット アクセスが検出されました。キャプティブ ポータルは、インターネットを自由に閲覧するアクセス権を得る前に、ネットワークのユーザーが表示し操作する必要のあるウェブサイトです。",
    "description": "Title for when a potential problem is found with the HTTP captive portal test."
  },
  "captiveportalhttptest_no_problem_threshold": {
    "message": "すべての HTTP リクエストで 204 HTTP ステータス コードが返された場合、HTTP キャプティブ ポータル テストでは問題なしという結果が返されます",
    "description": "Log record for the criteria under which the Captive Portal HTTP request returns a no problem verdict"
  },
  "captiveportalhttptest_potentialproblem_threshold": {
    "message": "次の割合を上回る HTTP リクエストでネットワーク スタックの問題があった場合、HTTP キャプティブ ポータル テストでは問題の可能性ありという結果が返されます: ",
    "description": "Log record for the criteria under which the Captive Portal HTTP request returns a potential problem verdict"
  },
  "captiveportalhttptest_problem_threshold": {
    "message": "204 HTTP ステータス コードを返さない HTTP リクエストがあった場合、HTTP キャプティブ ポータル テストでは問題ありという結果が返されます",
    "description": "Log record for the criteria under which the Captive Portal HTTP request returns a problem verdict"
  },
  "captiveportalhttptest_log_network_error": {
    "message": "エラーが発生しました。リクエスト # / エラーのステータス: ",
    "description": "Logger record for when TCP connection breaks an HTTP request"
  },
  "captiveportalhttptest_log_response_code": {
    "message": "レスポンス番号 / HTTP レスポンス コード: ",
    "description": "Logger record for full HTTP response length"
  },
  "captiveportalhttptest_log_http_response": {
    "message": "レスポンス番号 / HTTP レスポンス ヘッダー: ",
    "description": "Logger record for full HTTP response length"
  },
  "captiveportalhttptest_log_response_length": {
    "message": "リクエスト番号 / レスポンスの全長: ",
    "description": "Logger record for when TCP connection breaks an HTTP request"
  },
  "httplatencytest_name": {
    "message": "Google ウェブサイト HTTP 待ち時間テスト",
    "description": "Name for the HTTP latency test"
  },
  "httplatencytest_problem_title": {
    "message": "Google へのウェブ リクエストに時間がかかりすぎました",
    "description": "Title for when a problem is found in the HTTP latency test"
  },
  "httplatencytest_potentialproblem_title": {
    "message": "Google へのウェブ リクエストに想定より時間がかかりました",
    "description": "Title for when a potential problem is found in the HTTP latency test"
  },
  "httplatencytest_noproblem_title": {
    "message": "Google ウェブサイトから迅速なレスポンスを受信しました",
    "description": "Title for when no problem is found in the HTTP latency test"
  },
  "httplatencytest_problem_subtitle": {
    "message": "Google ウェブサイトからのレスポンス受信に想定より時間がかかっています。ネットワーク遅延の可能性があります。",
    "description": "Subtitle for when a problem is found in the HTTP latency test"
  },
  "httplatencytest_potentialproblem_subtitle": {
    "message": "Google ウェブサイトからのレスポンスの受信に想定より少し時間がかかっています。ネットワーク遅延の可能性があります。",
    "description": "Subtitle for when a potential problem is found in the HTTP latency test"
  },
  "httplatencytest_noproblem_subtitle": {
    "message": "Google へのウェブ リクエストは迅速に受信されています。",
    "description": "Subtitle for when no problem is found in the HTTP latency test"
  },
  "httplatencytest_log_network_error": {
    "message": "エラーが発生しました。リクエスト # / エラーのステータス: ",
    "description": "Logger record for when TCP connection breaks an HTTP request"
  },
  "httplatencytest_log_average_time": {
    "message": "HTTP レスポンスの平均時間（ミリ秒）: ",
    "description": "Logger record for when TCP connection breaks an HTTP request"
  },
  "httplatencytest_log_num_requests": {
    "message": "HTTP リクエストの合計数: ",
    "description": "Logger record for the total number of HTTP requests"
  },
  "httplatencytest_log_response_time": {
    "message": "HTTP レスポンスの合計時間（ミリ秒）: ",
    "description": "Logger record for the total HTTP response time"
  },
  "httplatencytest_log_response_details": {
    "message": "HTTP レスポンス # / 受信時刻（マイクロ秒単位のタイムスタンプ） / 経過時間（ミリ秒）: ",
    "description": "Logger record for the details of a specific response"
  },
  "httplatencytest_no_problem_time": {
    "message": "HTTP の応答にかかった平均時間（ミリ秒）のベンチマーク（下回ったとき、問題なしという結果を表示）: ",
    "description": "Logger record for http latency time for which we render a no problem verdict."
  },
  "httplatencytest_potential_problem_time": {
    "message": "HTTP の応答にかかった平均時間（ミリ秒）のベンチマーク（範囲内のとき、問題の可能性ありという結果を表示）: ",
    "description": "Logger record for http latency time for which we render a potential problem verdict."
  },
  "httplatencytest_problem_time": {
    "message": "HTTP の応答にかかった平均時間（ミリ秒）のベンチマーク（上回ったとき、問題ありという結果を表示）: ",
    "description": "Logger record for http latency time for which we render a problem verdict."
  },
  "chromeossignalstrengthtest_name": {
    "message": "Chrome OS の Wi-Fi 信号強度テスト",
    "description": "Name for the ChromeOS Signal Strength test"
  },
  "chromeossignalstrengthtest_failure_title": {
    "message": "Wi-Fi 信号強度テストが中断されました",
    "description": "Title for when a test failure occurs with ChromeOS Signal Strength test"
  },
  "chromeossignalstrengthtest_failure_subtitle": {
    "message": "テストを実行できませんでした。Wi-Fi 接続が検出されませんでした。",
    "description": "Subtitle for when a test failure occurs with ChromeOS Signal Strength test"
  },
  "chromeossignalstrengthtest_problem_title": {
    "message": "ネットワークの信号強度は「弱い」",
    "description": "Title for when a problem is found in the ChromeOS signal strength"
  },
  "chromeossignalstrengthtest_problem_subtitle": {
    "message": "Wi-Fi ネットワークの信号強度は「弱い」です。",
    "description": "Subtitle for when a problem is found in the ChromeOS signal strength"
  },
  "chromeossignalstrengthtest_noproblem_title": {
    "message": "ネットワークの信号強度は「強い」",
    "description": "Title for when no problem is found in the ChromeOS signal strength"
  },
  "chromeossignalstrengthtest_noproblem_subtitle": {
    "message": "Wi-Fi ネットワークの信号強度は「強い」です。",
    "description": "Subtitle for when no problem is found in the ChromeOS signal strength"
  },
  "chromeossignalstrengthtest_log_signal_strength": {
    "message": "ネットワーク信号名 / 信号強度: ",
    "description": "Logger record for the signal strength of a ChromeOS NIC connection"
  },
  "chromeossignalstrengthtest_no_problem_strength": {
    "message": "Chrome OS の信号強度のベンチマーク（上回ったとき、問題なしという結果を表示）: ",
    "description": "Logger record for signal strength for which we render a no problem verdict."
  },
  "chromeossignalstrengthtest_problem_strength": {
    "message": "Chrome OS の信号強度のベンチマーク（下回ったとき、問題ありという結果を表示）:",
    "description": "Logger record for signal strength for which we render a problem verdict."
  },
  "pinggatewaytest_name": {
    "message": "ゲートウェイの ping テスト",
    "description": "Name for the ping gateway test"
  },
  "pinggatewaytest_problem_title": {
    "message": "ゲートウェイを ping できません",
    "description": "Title for when a problem is found in the ping gateway test"
  },
  "pinggatewaytest_problem_subtitle": {
    "message": "ゲートウェイを ping しても迅速な応答が返されません。",
    "description": "Subtitle for when a problem is found in the ping gateway test"
  },
  "pinggatewaytest_noproblem_title": {
    "message": "ゲートウェイにアクセス可能",
    "description": "Title for when no problem is found in the ping gateway test"
  },
  "pinggatewaytest_noproblem_subtitle": {
    "message": "ゲートウェイを ping して迅速な応答が返されました。",
    "description": "Subtitle for when no problem is found in the ping gateway test"
  },
  "pinggatewaytest_no_problem_time": {
    "message": "ゲートウェイの ping にかかった時間（ミリ秒）のしきい値（下回ったとき、問題なしという結果を表示）: ",
    "description": "Logger record for the gateway latency below which we render a no problem verdict."
  },
  "pinggatewaytest_problem_time": {
    "message": "ゲートウェイの ping にかかった時間（ミリ秒）のしきい値（上回ったとき、問題ありという結果を表示）: ",
    "description": "Logger record for the gateway latency above which we render a problem verdict."
  },
  "pinggatewaytest_log_failure": {
    "message": "ゲートウェイの IP に直接送信された ICMP クエリで応答パケットを受信しませんでした。",
    "description": "Logger record for when there is no response to an ICMP packet"
  },
  "pinggatewaytest_log_latency": {
    "message": "ICMP パケットの待ち時間（ミリ秒）: ",
    "description": "Logger record for the latency of an ICMP packet in the ping gateway test"
  },
  "pinggatewaytest_log_gateway_unknown": {
    "message": "ゲートウェイの IP を特定できませんでした",
    "description": "Logger record for when the gateway of the IP could not be determined"
  },
  "pinggatewaytest_log_gateway_known": {
    "message": "ゲートウェイの IP を特定しました: ",
    "description": "Logger record for the gateway of the IP"
  },
  "pinggatewaytest_log_same_ip_response": {
    "message": "TTL を 1 に設定しているリモートホストへの ICMP パケット送信で、次のリモートホストの IP と同じ IP が返されました: ",
    "description": "Logger record for when the IP that is pinged returns the terminal destination IP and not the gateway IP"
  },
  "hangoutsblockedtest_name": {
    "message": "ハングアウト接続テスト",
    "description": "Name for the Hangouts blocked test"
  },
  "hangoutsblockedtest_noproblem_title": {
    "message": "ハングアウトに接続できます",
    "description": "Title for when no problem is found in the Hangouts blocked test"
  },
  "hangoutsblockedtest_noproblem_subtitle": {
    "message": "ハングアウト サービスに正常に接続しました。",
    "description": "Subtitle for when no problem is found in the Hangouts blocked test"
  },
  "hangoutsblockedtest_potentialproblem_title": {
    "message": "ハングアウトへの接続速度が一時的に低下しているようです",
    "description": "Title for when a potential problem is found in the Hangouts blocked test"
  },
  "hangoutsblockedtest_potentialproblem_subtitle_udp_media_blocked": {
    "message": "UDP ポート 19302～19309 でハングアウト メディア サービスに接続できません。",
    "description": "Subtitle for when a potential problem is found from the Hangouts blocked test whereby UDP is blocked to Hangouts media host."
  },
  "hangoutsblockedtest_problem_title": {
    "message": "ハングアウトへの接続を確立できませんでした",
    "description": "Title for when a problem is found from the Hangouts blocked test"
  },
  "hangoutsblockedtest_problem_subtitle": {
    "message": "ハングアウトへの接続に必要なポートとホストがブロックされているようです。",
    "description": "Subtitle for when a problem is found from the Hangouts blocked test"
  },
  "hangoutsblockedtest_problem_subtitle_udp_media_tcp_media_blocked": {
    "message": "TCP ポート 443 と UDP ポート 19302～19309 でハングアウト メディア サービスに接続できません。",
    "description": "Subtitle for when a problem is found from the Hangouts blocked test whereby TCP and UDP is blocked to Hangouts media host."
  },
  "hangoutsblockedtest_problem_subtitle_tcp_chat_blocked": {
    "message": "ハングアウト チャット サービスに接続できません。",
    "description": "Subtitle for when a problem is found from the Hangouts blocked test whereby TCP is blocked to Hangouts chat hosts."
  },
  "hangoutsblockedtest_problem_subtitle_tcp_media_tcp_chat_blocked": {
    "message": "TCP ポート 443 でハングアウト チャット サービスとハングアウト メディア サービスに接続できません。",
    "description": "Subtitle for when a problem is found from the Hangouts blocked test whereby TCP is blocked to Hangouts chat hosts."
  },
  "hangoutsblockedtest_log_tcp_connection_success": {
    "message": "ポート 443 で TCP 接続に成功しました。ホスト: ",
    "description": "Log record for when a TCP connection succeeds on port 443 to a required host"
  },
  "hangoutsblockedtest_log_tcp_connection_failure": {
    "message": "ポート 443 で TCP 接続がブロックされているため、接続に失敗しました。ホスト: ",
    "description": "Log record for when a TCP connection appears to be blocked on port 443 to a required host"
  },
  "hangoutsblockedtest_log_udp_connection_failure": {
    "message": "宛先ポートで UDP 接続がブロックされているため、接続に失敗しました。ポート: ",
    "description": "Log record for when a UDP connection appears to be blocked"
  },
  "hangoutsblockedtest_log_udp_connection_success": {
    "message": "宛先ポートで UDP 接続に成功しました。ポート: ",
    "description": "Log record for when a UDP connection can successfully send and receive data"
  },
  "hangoutsblockedtest_no_problem_criteria": {
    "message": "次の場合はハングアウト接続テストで問題なしという結果が返されます: （1）19302～19309 のいずれかの UDP ポートで stun.l.google.com への接続を確立できる場合 （2）apis.google.com、clients6.google.com、plus.google.com、talkgadget.google.com への TCP 接続を確立できる場合",
    "description": "Criteria under which the Hangouts blocked test returns a no problem verdict"
  },
  "hangoutsblockedtest_problem_criteria": {
    "message": "次の場合はハングアウト接続テストで問題ありという結果が返されます: （1）19302～19309 のすべての UDP 宛先ポートで stun.l.google.com への接続がブロックされている場合 （2）ポート 443 で apis.google.com、clients6.google.com、plus.google.com、talkgadget.google.com のいずれかのホストへの TCP 接続に失敗した場合",
    "description": "Criteria under which the Hangouts blocked test returns a problem verdict"
  },
  "wifiencryptiontest_name": {
    "message": "Wi-Fi 暗号化テスト",
    "description": "Name for the WiFi Encryption test"
  },
  "wifiencryptiontest_failure_title": {
    "message": "Wi-Fi 暗号化テストが中断されました",
    "description": "Title for when the WiFi Encryption test is not run"
  },
  "wifiencryptiontest_failure_subtitle": {
    "message": "Wi-Fi 暗号化テストは実行されていません。Wi-Fi ネットワークがありません。",
    "description": "Subtitle for when the WiFi Encryption test is not run"
  },
  "wifiencryptiontest_noproblem_title": {
    "message": "Wi-Fi 暗号化方式は強力です",
    "description": "Title for when no problem is found in the WiFi Encryption  blocked test"
  },
  "wifiencryptiontest_noproblem_subtitle": {
    "message": "お使いのパソコンで使用されている Wi-Fi 暗号化方式は強力です。",
    "description": "Subtitle for when no problem is found in the WiFi Encryption test"
  },
  "wifiencryptiontest_potentialproblem_title": {
    "message": "Wi-Fi 暗号化方式は部分的にのみ安全です",
    "description": "Title for when a potential problem is found in the WiFi encryption test"
  },
  "wifiencryptiontest_potentialproblem_subtitle": {
    "message": "ネットワーク接続で使用されている Wi-Fi 暗号化方式の強度は十分ではありません。",
    "description": "Subtitle for when a potential problem is found from the WiFi encryption test"
  },
  "wifiencryptiontest_problem_title": {
    "message": "Wi-Fi ネットワーク暗号化方式は安全ではありません",
    "description": "Title for when a problem is found from the WiFi encryption test"
  },
  "wifiencryptiontest_problem_subtitle": {
    "message": "ネットワーク接続で使用されている Wi-Fi ネットワーク暗号化方式は安全ではありません。",
    "description": "Subtitle for when a problem is found from the WiFi encryption test"
  },
  "wifiencryptiontest_problem_threshold": {
    "message": "問題ありという結果を表示する Wi-Fi 暗号化方式: ",
    "description": "Logger record for criteria when WiFi encryption test renders a problem"
  },
  "wifiencryptiontest_noproblem_threshold": {
    "message": "問題なしという結果を表示する Wi-Fi 暗号化方式: ",
    "description": "Logger record for criteria when WiFi encryption test renders a no problem"
  },
  "wifiencryptiontest_potentialproblem_threshold": {
    "message": "Wi-Fi 暗号化方式の安全性が不明な場合は、潜在的な問題ありと表示",
    "description": "Logger record for criteria when WiFi encryption test renders a potential problem"
  },
  "wifiencryptiontest_log_available_networks": {
    "message": "検出された使用可能なネットワークの数: ",
    "description": "Logger record for how many networks chrome.networkingPrivate found."
  },
  "wifiencryptiontest_log_network_encryption": {
    "message": "現在接続中の Wi-Fi ネットワークで使用されている暗号化方式: ",
    "description": "Logger record for the type of encryption used by the currently connected network"
  },
  "endtoendtest_name": {
    "message": "エンドツーエンドの Google ウェブサイト テスト",
    "description": "Name for End-to-End Google Website test."
  },
  "endtoendtest_noproblem_title": {
    "message": "Google ウェブサイトは利用可能です",
    "description": "Title for when no problem is found with the end-to-end Google website test."
  },
  "endtoendtest_noproblem_subtitle": {
    "message": "Google ウェブサイトは、接続の問題なく正常に読み込まれるようです。",
    "description": "Subtitle for when no problem is found with the end-to-end Google website test."
  },
  "endtoendtest_problem_title": {
    "message": "Google ウェブサイトは、正常な取得と読み込みができませんでした。",
    "description": "Title for when a problem is found with the end-to-end Google website test."
  },
  "endtoendtest_problem_subtitle": {
    "message": "Google ウェブサイトにアクセスしようとして問題が発生しました。この原因としては、キャプティブ ポータル、DNS 汚染、中間者攻撃などのネットワークの不正行為を含む、さまざまな問題が考えられます。",
    "description": "Subtitle for when a problem is found with the end-to-end Google website test."
  },
  "endtoendtest_no_problem_threshold": {
    "message": "テスト対象の Google サービス ウェブサイトのすべてで HTTPS 接続を確立できる場合、Google ウェブサイトへのエンドツーエンド アクセスは正常とみなされます",
    "description": "Log record for the threshold of no problem"
  },
  "endtoendtest_problem_threshold": {
    "message": "テスト対象の Google サービス ウェブサイトのいずれかで HTTPS 接続を確立できない場合、Google ウェブサイトへのエンドツーエンド アクセスには問題があるとみなされます",
    "description": "Log record for the threshold of a problem"
  },
  "endtoendtest_beginning_resolution": {
    "message": "テスト # / テストするホスト名: ",
    "description": "Logger record for noting a new XHR is sent to check Google site availability."
  },
  "endtoendtest_error_in_request": {
    "message": "次のホスト名に接続しようとしてエラーが発生しました。再試行します: ",
    "description": "Logger record for when an error occurs trying to connect to a Google hostname."
  },
  "endtoendtest_error_in_request_on_final": {
    "message": "次のホスト名への接続で、エラーが継続的に発生しています。接続に関する問題があるようです: ",
    "description": "Logger record for when XHR to check Google website availability."
  },
  "endtoendtest_success_request": {
    "message": "次のホスト名のリクエストは正常に終了しました。ステータス コード: ",
    "description": "Logger record for when an XHR request to check Google website availability"
  }
}